### ISSUE TITLE
You will got too big availableBadActions counter if iterate over all cards in hand.

### ISSUE THREAD

**Issue by capgreen** [societe-generale/GreenCircle#7]
https://github.com/societe-generale/GreenCircle/blob/9a434371343c0526139cb5b56902af2e7b518834/src/main/java/com/codingame/game/Application.java#L43

**Comment by ghost** [comment]
I don't get your issue. Do you mean the value will be too big for the type int?
We have at most 15 cards so the value won't be more than 30.

If you mean that we will get too much technical debt, don't worry. This availableBadActions is the max value. We will always use the minimum amount of bad actions required to release an application (look at the line 70 in your link).

**Comment by capgreen** [comment]
It seems to me that this code implies that cards that are not bonuses or skills necessary for the application can be used for the release of the application.

**Comment by ghost** [comment]
Yes: every "non Technical Debt" card in hand (or in AUTOMATED) can be used to release an application.
You can use them for the right skill (or for a bonus one)
You can also use them for shoddy skills. This variable availableBadActions is the max shoddy skills you have in hand. But you will not use all of them. 
We begin by using the correct skills. And we keep track of the missing skills in the variable missingResources.
Then we deduce the bonus skills from  missingResources.
Now  missingResources si the amount of skills you are missing. So the number of shoddy skills you will have to use to release the application.
availableBadActions is only used to check that we have enough shoddy skills to replace all the missingResources. But the technical debt you'll get is based on missingResources only.
Is that clearer? Or did I miss your point?

**Comment by capgreen** [comment]
Thank you for the clarification. 
So, is it possible to release the application with a penalty greater than 4?

**Comment by ghost** [comment]
Yes it is. If you only have 4 CODING cards and an application needs 4 REFACTORING skills and 4 TRAINING skills, you can release it with only 8 shoddy skills and get 8 technical debts. 
So it is possible, but I advise you not to do it since this is a lot of debt ;)
